### ISSUE TITLE
Search through the Unit website to find out what issues are missed

### ISSUE THREAD

**Issue by frinzekt** [UWA-CITS3200-18-2021/ReSQ#10]
## Basic Information
This task is about scanning through the unit website and generating github issues, this will help us when deadlines comes up, and visibility in the team, to who does what?

See https://teaching.csse.uwa.edu.au/units/CITS3200/index.html

**Comment by Alexkszzz** [comment]
### Upcoming events and deadlines of August

![image](https://user-images.githubusercontent.com/88120461/128489773-a426f1ab-a0f1-4d07-aa40-6a6399f99dac.png)

**Comment by frinzekt** [comment]
It is believed that we have converted the tasks in the unit website to github issues or something similar
