### ISSUE TITLE
vulnerable dependency in yarn.lock

### ISSUE THREAD

**Issue by TheOneHoff** [UWA-CITS3200-18-2021/ReSQ#101]
## Basic Information

- The vulnerable dependency that github auto detected is in yarn.lock 
- line 107

## Other Information

- Is this needed in testing?
- If not necessary, probably best to remove it, otherwise its not a very good look to the markers

**Comment by frinzekt** [comment]
Don't worry much about these vulnerabilities, read the report before deciding to do anything... If you try to address all these vulnerabilities, you're going to spend quite a long time.

If you want to automatically resolve this, I can turn on dependabot. Turning dependabot is also distracting take a look at this 
https://github.com/uwasystemhealth/livinglab-site-v3/pulls ... Some automatic dependency update is also breaking the software

**Comment by frinzekt** [comment]
Yarn.lock is only used for automated testing... Not used for production, so leave it alone

**Comment by frinzekt** [comment]
Vulnerability is determined if your dependency or any of its subdependencies are vulnerable. This project easily have 1000+ subdependencies in these days and age. Hence it's quite frequent to get an alert about it once in a while.

In a professional setting, updating the dependency is done on a periodic basis such as twice per year, not every day or every week as it delivers no direct value to business

**Comment by TheOneHoff** [comment]
That is understandable. I was just wondering if it was an easy fix or not. If it is not easy, then you're right and we will just leave it for the time being

**Comment by frinzekt** [comment]
It's an easy fix, the only downside is, I don't know what it may break it I fix it
