### ISSUE TITLE
Setup a continuous integration pipeline

### ISSUE THREAD

**Issue by frinzekt** [UWA-CITS3200-18-2021/ReSQ#12]
## Basic Information
Software reliability is important. However, manual testing is quite hard when it has to be done for every little change that is done in a software.

## Other Information
You can implement this with Github action. In terms of the technical bits about how to test, you may want to take a look into Cypress (end to end testing) - very widely use in web. See https://github.com/uwasystemhealth/IndEAA/actions/runs/1036173200

**Comment by lmbhov** [comment]
Cypress will be used to create videos of the main workflow of the website to allow bugs to be easily identified with every commit.
Software will need to be chosen for the linting of the majority of the codebase. Flake8 may be used for python sections.

**Comment by frinzekt** [comment]
The group does not currently have skill nor time to implement this

**Comment by frinzekt** [comment]
I'll be reviving this issue as part of acceptance test of sprint 3

**Comment by JordanHartley** [comment]
Abandoned this issue because of difficulty and time constraints.
