### ISSUE TITLE
Creating a figma/canva/mockups prototype for interface design 

### ISSUE THREAD

**Issue by lmbhov** [UWA-CITS3200-18-2021/ReSQ#14]
## Basic Information
Create an interface prototype to tackle what needs to be done to create the solution for #3 

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by JordanHartley** [comment]
![ReSQ_Mockup](https://user-images.githubusercontent.com/81401309/128977149-e059fd03-0cb6-4337-8b26-86681b27f92c.png)

Just an initial mockup for the basic layout of the UI for the student leader, open to any ideas and comments.

**Comment by Alexkszzz** [comment]
It'll be great to discuss this tmr and email the client to ask for his feedback
