### ISSUE TITLE
Set of Stories (Initial from Sprint 1)

### ISSUE THREAD

**Issue by JordanHartley** [UWA-CITS3200-18-2021/ReSQ#17]
## Basic Information
The set of stories to be completed in sprint 2

## Other Information
t is recommended that you also create a set of intermediate acceptance criteria to assess the products of that Sprint for your internal use, but these will not assessed

**Comment by lmbhov** [comment]
This will come from #3 and #4

**Comment by lmbhov** [comment]
[Sprint 2 Stories.docx](https://github.com/UWA-CITS3200-18-2021/ReSQ/files/7005162/Sprint.2.Stories.docx)

Please review the draft of Sprint Two stories.

**Comment by lmbhov** [comment]
Moved two Sprint Two milestone, as these are the goals needed for Sprint two

**Comment by lmbhov** [comment]
"Given the Agile methodology that we are using in this unit, there is some abiguity in the deliverables due at the end of this Sprint. In essence, what your team should deliver (or demonstrate, as appropriate) are the set of interim goals you proposed at the end of Sprint 1. While the final system has to be delivered on the Client's choice of hardware, for this Sprint's deliverables it is sufficient that the goals be demonstrated on the development platform."

**Comment by lmbhov** [comment]
[Sprint_2_Stories.docx](https://github.com/UWA-CITS3200-18-2021/ReSQ/files/7011121/Sprint_2_Stories.docx)
