### ISSUE TITLE
Skills Audit

### ISSUE THREAD

**Issue by lmbhov** [UWA-CITS3200-18-2021/ReSQ#18]
## Basic Information
document individual skills of the team

## Other Information
Refer back to SWOT Analysis

**Comment by Alexkszzz** [comment]
###Alex Mai

Strengths: 
- Python, C++, flexible
- Average: Java, frontend, data structures, math

Weaknesses: Coding practice

Opportunities: 
- Having the chance to improve coding practice as well as teamworking
- Learn more about project management

**Comment by frinzekt** [comment]
# Frinze

## Strengths

- Strong: Python [Django + PostgreSQL] , JavaScript (HTML + CSS) [MongoDB + Express + React + Node]
- familiarity on UWA Infrastructure (works as software engineer in the UWA System Health Lab)
- Docker
- Git (gitkraken) and GitHub 
- Full-stack web development (both frontend + backend)
- software engineering practices
- code pattern (full-stack style) / coding practices
- documentation + paperworks
- project management
- end-to-end software delivery SDLC (stakeholder management + requirements to development to deployment + maintenance)

## Weaknesses

- mathematics + statistics
- data science / AI / ML / NLP (familiar, but not much exposure)
- IoT (familiar, but not much exposure)
- Systems (Java + C/C++)
- time / availability
- cybersecurity
- other subject (chemistry, physics) / context-specific problems

## Opportunities

- full stack web development

## Threats

- Scope creep (as per weakness of time)
- Technical debt

**Comment by Jake22484785** [comment]
Strengths:

- Systems programming C and Java
- Data science analysing data and visual presentation 
- Average in mySql / database 

Weaknesses:

- Time
- Python 
- Web dev backend / JavaScript 

Opportunities:

- Learn how to do testing 
- improve poor web dev skills / learn JavaScript 
- Learn how to work in group project environment

**Comment by TheOneHoff** [comment]
Template for skills/resources audit
[Skills_Audit_[YOUR NAME HERE].docx](https://github.com/UWA-CITS3200-18-2021/ReSQ/files/6999560/Skills_Audit_.YOUR.NAME.HERE.docx)

**Comment by TheOneHoff** [comment]
Final Document for review
[CITS3200_Skills_Audit_Group_18.docx](https://github.com/UWA-CITS3200-18-2021/ReSQ/files/7004968/CITS3200_Skills_Audit_Group_18.docx)

**Comment by lmbhov** [comment]
Looks Good! Unfortunately the criteria for marking seems very vague;

0 | No skills audit
1 | Just a token effort
2 | Rudimentary, but some evidence of thought
3 | Solid audit of what the Team has versus what will be required for the project
4 | The Team has really thought of everything


Maybe for point 3 you could mention how our preferred software changed from Javascript to python/Flask based off the skills audit?

**Comment by TheOneHoff** [comment]
Good point. Added into the document
[CITS3200_Skills_Audit_Group_18.docx](https://github.com/UWA-CITS3200-18-2021/ReSQ/files/7005026/CITS3200_Skills_Audit_Group_18.docx)
