### ISSUE TITLE
Version Control guide on Github

### ISSUE THREAD

**Issue by Alexkszzz** [UWA-CITS3200-18-2021/ReSQ#21]
## Basic Information
A tutorial for version management while using Github. (Feels free to skip this issue if you're familiar with it already)

## Other Information
I found this tutorial very useful for Github version control since we are all working on the same repo and it is very likely to mess up the files since there might be many people working on a file at the same time.
https://ourcodingclub.github.io/tutorials/git/
** Main points**

- "always Pull before you Push"
- "be aware that if there are other people that have committed to the repository, reverting will also undo all of their work, as reverting refers to the repository as a whole, not just your own work in it."
- Sync and interact with your repository through the command line
 - Each issue will be on a separate branch, when you're satisfied with ur work, you can make a 'pull request' to merge the current branch into the main branch. (see https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches)

**Comment by frinzekt** [comment]
I think something good to point out here is that each issue will be on a separate branch

**Comment by Alexkszzz** [comment]
> I think something good to point out here is that each issue will be on a separate branch

Oooh I see the meaning of that just now

**Comment by frinzekt** [comment]
Yeah,

This is basically what that looks like
![image](https://user-images.githubusercontent.com/44391389/128725513-7a49dd2c-33c8-4478-9b83-e2b705bfe7af.png)

Each issue is assigned to a branch, and the issue has an assigned pull request that goes in eg. #13  #2
