### ISSUE TITLE
Add/Remove students from queue and move students to in-session queue

### ISSUE THREAD

**Issue by frinzekt** [UWA-CITS3200-18-2021/ReSQ#28]
## Basic Information
I want to be able to easily add students to the queue and remove them from the queue when they leave or are being seen, so that the website replaces the core features of the existing technology. 

## Other Information
A simple input system is on the website allowing quick entering of information. People can be removed from the queue at any time.

**Comment by Alexkszzz** [comment]
https://medium.com/@singh.surbhicse/creating-audit-table-to-log-insert-update-and-delete-changes-in-flask-sqlalchemy-f2ca53f7b02f
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-iv-database

**Comment by frinzekt** [comment]
Closed by #38
