### ISSUE TITLE
Requirements Gathering

### ISSUE THREAD

**Issue by frinzekt** [UWA-CITS3200-18-2021/ReSQ#3]
## Basic Information
This task is about liasing with the client to gather the requirements

This will be a collective task, however he/she will be the main point of contact whenever communicating. 

## Other Information
The goal that we have here is to consolidate what needs to be done for the project. Main points are:

- Aim and Scope (the problem we are trying to solve, and the issues there are in the current system)
- The features that are considered as MVP (minimum viable product)

Here's an example of an artefact that will result from this liasing https://aser-docs.systemhealthlab.com/developer/requirements/, the requirements document

### More about MVP
Identifying MVP is important to determine which features delivers the most amount of value. This means that, if there are "fancy features" that the client doesn't even need, we can cut that in the development. Saving us a lot of time

### After Requirements
We need to decide properly on what tech we are going to pick with a discussion as to why we are building one (if we are choosing to build rather than use an existing design solution)

**Comment by frinzekt** [comment]
## Problem

### Queue management (priority 1)
Service in the library as a dropin to get support in any element
- research
- writing
- referencing
- study

Start up quite slow in the semester, but it gets really busy. Student leader, sign in service. Problems whenever theres turnover of lectures

### Data usage reporting (priority 2)
report
- when the busy times
- the topics of the busy times

Usage report
- how many students
- what do they ask
- where the busy times are

Note: This is "nice-2-have"

## Current Tech
- uses Excel and shows (will be sent by Adam)

## Current solution
Triage point
- client
- self-service

Agreement is to make it as low-barrier at a time. Maybe both having a self-service point + client.

## Other notes
Usual cap time is around 15-20 minutes per students.

Similarity to Computer Lab sessions:
- see as many student as can withtin the allotted time

## Existing design solution
Unihub drop platform
- does not need the same level

**Comment by lmbhov** [comment]
This has to cover both:
- scope of work
- project acceptance test

**Comment by lmbhov** [comment]
Risk register CLE = R (consequence * likelyhood * exposure = risk)

**Comment by frinzekt** [comment]
@Alexkszzz  need to follow up on the sample excel file to track students in the queue

**Comment by frinzekt** [comment]
Just going to put this here https://lucid.app/lucidchart/invitations/accept/inv_1d4b0ed7-fb98-4a2a-b338-c7a1513e9716?viewport_loc=-423%2C96%2C2219%2C1108%2C0_0 (this contains the Entity Relationship Diagram)

**Comment by frinzekt** [comment]
This has been done as part of scope of work and is uploaded in onedrive
