### ISSUE TITLE
HTML Limit character for queue form 

### ISSUE THREAD

**Issue by Alexkszzz** [UWA-CITS3200-18-2021/ReSQ#40]
## Basic Information
It will be nice to have character limit in the Add to queue form. Can have a look at limit character HTML. 

https://www.w3schools.com/tags/att_input_maxlength.asp

**Comment by JordanHartley** [comment]
This feature has been added in c52-incorrect-input-feedback. Suggesting to close the issue.

**Comment by Alexkszzz** [comment]
For more info, see #52
