### ISSUE TITLE
Current session does not keep the changing color when reloading the page

### ISSUE THREAD

**Issue by Alexkszzz** [UWA-CITS3200-18-2021/ReSQ#50]
## Basic Information
When reloading the page, sessions with over 10 minutes will not keep its warning color.

**Comment by JordanHartley** [comment]
Easy fix? Could change this:

if (timers[id] == 600) {
		document.getElementById(id).className = 'yellowTime';
	}
	if (timers[id] == 1200) {
		document.getElementById(id).className = 'orangeTime';
	}
	if (timers[id] == 1800) {
		document.getElementById(id).className = 'redTime';
	}
}

To this:?

if (timers[id] >= 600 && timers[id] < 1200) {
		document.getElementById(id).className = 'yellowTime';
	}
	if (timers[id] >= 1200 && timers[id] < 1800) {
		document.getElementById(id).className = 'orangeTime';
	}
	if (timers[id] >= 1800) {
		document.getElementById(id).className = 'redTime';
	}
}

**Comment by frinzekt** [comment]
sounds good

**Comment by Alexkszzz** [comment]
Tested, this works well! Commited in C36
