### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by TheOneHoff** [UWA-CITS3200-18-2021/ReSQ#59]
## Basic Information
In order to ensure the stability and reliability of our application, testing using a tool like pytest should be done

## Other Information
**[Are there any additional information that we should know about?]**

**Comment by TheOneHoff** [comment]
Focus on interface testing

**Comment by frinzekt** [comment]
Some discussion happened in #12

**Comment by frinzekt** [comment]
I will be handling the technical side of this, so if someone can take care of the paper works that will be great refer to #24

**Comment by frinzekt** [comment]
Here are the testing artifacts

Code Coverage
[htmlcov.zip](https://github.com/UWA-CITS3200-18-2021/ReSQ/files/7332015/htmlcov.zip)

Test Result Reports can be found here
https://allure.systemhealthlab.com

Video recordings are here


https://user-images.githubusercontent.com/44391389/137001823-f92c10c2-9f8e-41b8-aa7a-d073a88979fa.mp4


https://user-images.githubusercontent.com/44391389/137001841-419cd9d7-ae5d-4433-b0bf-23ab3a8cfe86.mp4


https://user-images.githubusercontent.com/44391389/137001842-ccb161be-b462-4792-bc15-886051290747.mp4


https://user-images.githubusercontent.com/44391389/137001846-7a9d04ab-33cd-4e98-afe0-fd88f3060e5f.mp4

**Comment by Alexkszzz** [comment]
close by #94 #68
